# Generated by Django 4.0.1 on 2022-01-11 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_test_resulturl_alter_test_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
